-- Create Tables
create table jobs (
  id bigint generated by default as identity primary key,
  company text not null,
  title text not null,
  location text,
  contract_type text,
  salary text,
  source text,
  compatibility int,
  description text,
  skills jsonb,
  posted_date date,
  remote boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table applications (
  id bigint generated by default as identity primary key,
  job_id bigint references jobs(id) on delete cascade,
  user_id uuid references auth.users(id), -- Link to Supabase Auth User
  status text check (status in ('draft', 'pending', 'sent', 'responded', 'to_modify')),
  created_date date default current_date,
  sent_date date,
  response_date date,
  cover_letter text,
  custom_email text,
  notes text,
  cv_path text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table recruiters (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  linkedin text,
  company text,
  position text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Row Level Security)
alter table jobs enable row level security;
alter table applications enable row level security;
alter table recruiters enable row level security;

-- Policies
-- Jobs: Public read, Admin write (simplified to Public read for now)
create policy "Public jobs are viewable by everyone" on jobs for select using (true);

-- Applications: Users can CRUD their own applications
create policy "Users can view own applications" on applications for select using (auth.uid() = user_id);
create policy "Users can insert own applications" on applications for insert with check (auth.uid() = user_id);
create policy "Users can update own applications" on applications for update using (auth.uid() = user_id);
create policy "Users can delete own applications" on applications for delete using (auth.uid() = user_id);

-- Storage (Bucket: 'cvs')
insert into storage.buckets (id, name) values ('cvs', 'cvs');
create policy "CVs are publicly accessible" on storage.objects for select using (bucket_id = 'cvs');
create policy "Users can upload CVs" on storage.objects for insert with check (bucket_id = 'cvs' and auth.role() = 'authenticated');

-- Webhook Configuration
create table webhook_config (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) unique,
  outgoing_url text,
  secret text,
  enabled boolean default false,
  events jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table webhook_config enable row level security;
create policy "Users can view own webhook config" on webhook_config for select using (auth.uid() = user_id);
create policy "Users can insert own webhook config" on webhook_config for insert with check (auth.uid() = user_id);
create policy "Users can update own webhook config" on webhook_config for update using (auth.uid() = user_id);
create policy "Users can delete own webhook config" on webhook_config for delete using (auth.uid() = user_id);

-- Agent Actions / Logs
create table agent_actions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  event text,
  status text,
  result jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table agent_actions enable row level security;
create policy "Users can view own agent actions" on agent_actions for select using (auth.uid() = user_id);
create policy "Users can insert own agent actions" on agent_actions for insert with check (auth.uid() = user_id);
create policy "Users can delete own agent actions" on agent_actions for delete using (auth.uid() = user_id);
